name: CI

on: [pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Install RocksDB
        run: |
          sudo apt-get install python3-pip libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev librocksdb-dev
      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip
      - name: Install UnitTest dependencies
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install -e .[tests]
      - name: Run unit tests
        run: pytest -vx
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Remove unnecessary dependencies for test
        run: |
          echo "" > requirements.txt
      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip
      - name: Install lint dependencies
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install -e .[lint]
      - name: Lint
        run: flake8
