name: Unittest

on: [pull_request]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for rocksdb
        run: |
          sudo apt-get install python3-pip \
          libgflags-dev \
          libsnappy-dev \
          zlib1g-dev \
          libbz2-dev \
          liblz4-dev \
          libzstd-dev \
          librocksdb-dev
      - name: Install dependencies for lmdb
        run: |
          sudo apt-get install lmdb-utils
      - name: Install dependencies
        run: |
          python -V
          pip install -e .[dev]
      - name: Run unit tests
        run: pytest -vx
